receivers:
  otlp:
    protocols:
      grpc: 
processors:
  batch:
exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    const_labels:
      label1: value1
  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true
  logging:
extensions:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
